apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
          - sh
          - -c
          - |
            rm -rf /mnt/html/* /mnt/html/.[!.]* /mnt/html/..?* 2>/dev/null || true
            git clone https://github.com/facundoh3/static-website.git /mnt/html
        volumeMounts:
        - name: html-volume
          mountPath: /mnt/html
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: web-pvc
# persistentVolumeClaim:
        # emptyDir: {}

